import { faker } from "@faker-js/faker";
import { RecordTypeWrapper } from "../../../RecordTypeService/RecordTypesWrapper";
import { FakerJSRecipeFakerService } from "../FakerJSRecipeFakerService";

describe('FakerJSRecipeFakerService Shared Intstance Tests', () => {

    let fakerJSRecipeFakerService = new FakerJSRecipeFakerService();

    describe('getMapSalesforceFieldToFakerValue', () => {

        const fieldTypeToNPMFakerMappings = fakerJSRecipeFakerService.getMapSalesforceFieldToFakerValue();
        const placeholderForXMLMarkupDependentValue = 'GENERATED BY FIELD XML MARKUP';
        const referenceValuePlaceholder = '### TODO -- REFERENCE ID REQUIRED';
        const seeOnePagerPlaceholder = '### TODO -- SEE ONE PAGER - https://gist.github.com/jdschleicher/4abfd188a933598833285ee76e560445';

        test('Text field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['text']).toBe('${{ faker.lorem.text(5).substring(0, 255) }}');
        });

        test('TextArea field returns correct npm faker expression', () => {

            const textAreaExpression = fieldTypeToNPMFakerMappings['textarea'];
            expect(textAreaExpression).toBe('${{ faker.lorem.paragraph() }}');
            
        });

        test('LongTextArea field returns correct npm faker expression', () => {
            const longTextAreaExpression = fieldTypeToNPMFakerMappings['longtextarea'];
            expect(longTextAreaExpression).toBe('${{ faker.lorem.text(100) }}');
        });

        test('RichTextArea Html field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['html']).toBe('${{ faker.string.alpha(10) }}');
        });

        test('Email field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['email']).toBe('\${{ faker.internet.email() }}');
        });

        test('Phone field returns correct npm faker expression', () => {
            const phoneFakerExpression = fieldTypeToNPMFakerMappings['phone'];
            expect(phoneFakerExpression).toBe(`|
                \${{ faker.phone.number({style:\'national\'}) }}`);
        });

        test('Url field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['url']).toBe('\${{ faker.internet.url() }}');
        });

        test('Number field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['number']).toBe(`|
                \${{ faker.number.int({min: 0, max: 999999}) }}`);
        });

        test('Currency field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['currency']).toBe('\${{ faker.finance.amount(0, 999999, 2) }}');
        });

        test('Percent field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['percent']).toBe(`|
                \${{ faker.number.float({ min: 0, max: 99, precision: 0.01 }).toFixed(2) }}`);
        });

        test('Date field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['date']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'2023-01-01\'), to: new Date() }).toISOString().split(\'T\')[0] }}`);
        });

        test('DateTime field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['datetime']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'2023-01-01T00:00:00Z\'), to: new Date() }).toISOString() }}`);
        });

        test('Time field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['time']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'1970-01-01T00:00:00Z\'), to: new Date(\'1970-01-01T23:59:59Z\') }).toISOString().split(\'T\')[1] }}`);
        });

        test('Picklist field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['picklist']).toBe(placeholderForXMLMarkupDependentValue);
        });

        test('MultiselectPicklist field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['multiselectpicklist']).toBe(placeholderForXMLMarkupDependentValue);
        });

        test('Checkbox field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['checkbox']).toBe('\${{ faker.datatype.boolean() }}');
        });

        test('Lookup field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['lookup']).toBe(referenceValuePlaceholder);
        });

        test('MasterDetail field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['masterdetail']).toBe(referenceValuePlaceholder);
        });

        test('Formula field returns correct message', () => {
            expect(fieldTypeToNPMFakerMappings['formula']).toBe('### TODO - Formula fields are calculated, not generated - remove this line');
        });

        /*
            A Location field no longer reaches this map at all -- it is expanded into its Latitude
            and Longitude component fields before a recipe value is looked up, so the gist-link
            placeholder that stood in for that expansion has nothing left to describe.
        */
        test('Location field is absent from the map, so no recipe line can carry the one pager placeholder', () => {
            expect(fieldTypeToNPMFakerMappings).not.toHaveProperty('location');
            expect(Object.values(fieldTypeToNPMFakerMappings)).not.toContain(seeOnePagerPlaceholder);
        });

        test('All Salesforce field types have a corresponding mapping', () => {
            const expectedFields = [
                'text', 'textarea', 'longtextarea', 'html', 'email', 
                'phone', 'url', 'number', 'currency', 'percent', 'date', 
                'datetime', 'time', 'picklist', 'multiselectpicklist', 'checkbox', 
                'lookup', 'masterdetail', 'formula'
            ];

            expectedFields.forEach(field => {
                expect(fieldTypeToNPMFakerMappings).toHaveProperty(field);
            });
        });

        test('All mapping values are strings', () => {
            Object.values(fieldTypeToNPMFakerMappings).forEach(value => {
                expect(typeof value).toBe('string');
            });
        });

    });

    describe('generateTabs', ()=> {

        test('given 1 tab argument, returns expected spaces', () => {

            const expectedTabs = 4; 
            const actualTabResult = fakerJSRecipeFakerService.generateTabs(1);
            const actualSpacesCount = actualTabResult.length;
            expect(actualSpacesCount).toEqual(expectedTabs);

        });

    });

    describe('buildMultiSelectPicklistRecipeValueByXMLFieldDetail', () => {

        test('given expected list of choices, returns expected multiselect picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ (faker.helpers.arrayElements([`apple`,`orange`,`banana`])).join(';') }}";
            const emptyRecordTypeApiToRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildMultiSelectPicklistRecipeValueByXMLFieldDetail(possibleChoices, emptyRecordTypeApiToRecordTypeWrapperMap, fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

    });

    describe('buildDependentPicklistRecipeFakerValue', () => {

        test('given expected controlling value picklist options, returns expected dependent picklist faker value', () => {

            const expectedControllingValueToPicklistOptions: Record<string, string[]> = {
                Toyota: ["Corolla", "Camry", "Prius"],
                Ford: ["F-150", "Mustang", "Explorer"],
                Honda: ["Civic", "Accord", "Pilot"],
                Tesla: ["Model S", "Model 3", "Model X"],
            };            

            const controllingField = "CarBrand__c";
            
            const expectedDependentPicklistRecipeValue =`
      if:
        - choice:
            when: \${{ ${controllingField} == 'Toyota' }}
            pick:
                random_choice:
                    - Corolla
                    - Camry
                    - Prius
        - choice:
            when: \${{ ${controllingField} == 'Ford' }}
            pick:
                random_choice:
                    - F-150
                    - Mustang
                    - Explorer
        - choice:
            when: \${{ ${controllingField} == 'Honda' }}
            pick:
                random_choice:
                    - Civic
                    - Accord
                    - Pilot
        - choice:
            when: \${{ ${controllingField} == 'Tesla' }}
            pick:
                random_choice:
                    - Model S
                    - Model 3
                    - Model X`;


            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "CarModel__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildDependentPicklistRecipeFakerValue(expectedControllingValueToPicklistOptions, 
                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                        controllingField, 
                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedDependentPicklistRecipeValue);
        });

    });

    describe('buildPicklistRecipeValueByXMLFieldDetail', () => {

        test('given expected list of choices, returns expected  picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ faker.helpers.arrayElement([`apple`,`orange`,`banana`]) }}";
            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(possibleChoices, 
                                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

            test('given expected list of choices, returns expected  picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ faker.helpers.arrayElement([`apple`,`orange`,`banana`]) }}";
            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(possibleChoices, 
                                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

    });

    describe('getOOTBExpectedObjectToFakerValueMappings', () => { 

        test('given expected list of OOTB object keys, mapping keys are found', () => {
            
            const actualMappings = fakerJSRecipeFakerService.getOOTBObjectApiNameToFieldApiNameMap();

            const expectedObjectsInMappings = [
                'Account',
                'Contact',
                'Opportunity',
                'Lead',
                'Case',
                'Campaign',
                'Task',
                'Event',
                'Product2',
                'PriceBook2',
                'Asset',
                'Contract'
            ];

            expectedObjectsInMappings.forEach(objectName => {
                expect(objectName in actualMappings).toBe(true);
            });

            expect(Object.keys(actualMappings).length).toBe(expectedObjectsInMappings.length);

        });

    });


        /*
            A dependent picklist need not appear in a record type's picklist sections at all: the
            record type can expose the CONTROLLING field, with the controlling value available, and
            simply not include the dependent field. The lookup for the controlling field was guarded;
            the one for the dependent field two lines later was not, so this crashed recipe
            generation for the whole run rather than reporting the gap for one record type.
        */
        test('given a dependent field absent from the record type picklist sections, reports a TODO rather than throwing', () => {

            const recordTypeWrapperMap: Record<string, RecordTypeWrapper> = {
                OneRecType: {
                    DeveloperName: 'OneRecType',
                    // THE CONTROLLING FIELD IS PRESENT AND UNLOCKS "cle"; THE DEPENDENT FIELD IS NOT IN THIS RECORD TYPE
                    PicklistFieldSectionsToPicklistDetail: { 'Picklist__c': ['cle'] },
                    RecordTypeId: ''
                }
            };

            let actualChoicesBreakdown = '';

            expect(() => {
                actualChoicesBreakdown = fakerJSRecipeFakerService.updateDependentPicklistRecipeFakerValueByRecordTypeSections(
                    recordTypeWrapperMap,
                    'DependentPicklistNotInRecordType__c',
                    'Picklist__c',
                    'cle'
                );
            }).not.toThrow();

            expect(actualChoicesBreakdown).toContain('### TODO');
            expect(actualChoicesBreakdown).toContain('DependentPicklistNotInRecordType__c');
            expect(actualChoicesBreakdown).toContain('OneRecType');

        });


    /*
        Picklist options are untrusted text from field metadata or a global value set in whatever
        repository the user opened, and they are embedded in a JS template literal that
        FakerJSRecipeProcessor hands to new Function(). An unescaped backtick closes the literal and
        turns the rest of the value into executable code.
    */
    describe('escapePicklistOptionForTemplateLiteral', () => {

        const fakerJSRecipeFakerService = new FakerJSRecipeFakerService();

        test('given a value containing a backtick, escapes it so it cannot close the template literal', () => {

            const breakoutAttempt = 'a`,globalThis.INJECTED,`b';
            const generatedSyntax = fakerJSRecipeFakerService.buildPicklistFakerArraySingleElementSyntaxByPicklistOptions([breakoutAttempt]);

            expect(generatedSyntax).toContain('\\`');

            /*
                The text still APPEARS in the output -- escaped, it is inert data inside the literal.
                What proves that is evaluating it: the expression must yield the original value
                unchanged. Unescaped, the same input parses as a three-element list whose middle
                element is executable code, and this returns something else or throws.
            */
            const stubFaker = { helpers: { arrayElement: (options: string[]) => options[0] } };
            const evaluatedValue = new Function('faker', `return (${generatedSyntax})`)(stubFaker);

            expect(evaluatedValue).toBe(breakoutAttempt);

        });

        test('given a value containing a template interpolation, escapes it so it cannot be evaluated', () => {

            const generatedSyntax = fakerJSRecipeFakerService.buildPicklistFakerArraySingleElementSyntaxByPicklistOptions(['${process.env.SECRET}']);

            expect(generatedSyntax).toContain('\\${');
            expect(generatedSyntax).not.toMatch(/[^\\]\$\{process/);

        });

        test('given a value containing a backslash, escapes it first so it cannot re-escape the escaping', () => {

            expect(FakerJSRecipeFakerService.escapePicklistOptionForTemplateLiteral('back\\slash')).toBe('back\\\\slash');
            // A TRAILING BACKSLASH WOULD OTHERWISE ESCAPE THE CLOSING BACKTICK
            expect(FakerJSRecipeFakerService.escapePicklistOptionForTemplateLiteral('trailing\\')).toBe('trailing\\\\');

        });

        test('given a value containing a newline, escapes it so the recipe YAML structure survives', () => {

            expect(FakerJSRecipeFakerService.escapePicklistOptionForTemplateLiteral('a\nb')).toBe('a\\nb');

        });

        test('given ordinary values, leaves them byte-identical', () => {

            const ordinaryOptions = ['guardians', 'cavs', 'Ohio_City', 'Some Value'];
            ordinaryOptions.forEach(ordinaryOption => {
                expect(FakerJSRecipeFakerService.escapePicklistOptionForTemplateLiteral(ordinaryOption)).toBe(ordinaryOption);
            });

        });

        test('the escaped expression still parses as valid JavaScript', () => {

            const generatedSyntax = fakerJSRecipeFakerService.buildPicklistFakerArraySingleElementSyntaxByPicklistOptions(['a`,INJECTED,`b', "quote'value"]);

            expect(() => new Function('faker', `return (${generatedSyntax})`)).not.toThrow();

        });

    });

    describe('getAddressComponentToRecipeValueMap', () => {

        /*
            Pinned literally rather than read from RecipeService.compoundAddressComponentKeys: a faker
            service is a leaf that must not import the orchestrator, and the RecipeService suite
            already asserts the two lists agree by exercising the composition.
        */
        test('returns an expression for every compound address component, and only those', () => {

            const addressComponentToRecipeValue = fakerJSRecipeFakerService.getAddressComponentToRecipeValueMap();

            expect(Object.keys(addressComponentToRecipeValue)).toEqual(
                ['Street', 'City', 'State', 'PostalCode', 'Country']
            );

        });

        test('returns the expected faker-js location expressions', () => {

            const addressComponentToRecipeValue = fakerJSRecipeFakerService.getAddressComponentToRecipeValueMap();

            expect(addressComponentToRecipeValue['Street']).toBe('${{faker.location.streetAddress()}}');
            expect(addressComponentToRecipeValue['City']).toBe('${{faker.location.city()}}');
            expect(addressComponentToRecipeValue['State']).toBe('${{faker.location.state()}}');
            expect(addressComponentToRecipeValue['PostalCode']).toBe('${{faker.location.zipCode()}}');
            expect(addressComponentToRecipeValue['Country']).toBe('${{faker.location.country()}}');

        });

        /*
            The coded components only exist in an org with State and Country Picklists enabled, so
            emitting them by default would produce a recipe that fails to insert everywhere else.
        */
        test('uses the plain State and Country components, never StateCode or CountryCode', () => {

            const addressComponentToRecipeValue = fakerJSRecipeFakerService.getAddressComponentToRecipeValueMap();

            expect(addressComponentToRecipeValue).not.toHaveProperty('StateCode');
            expect(addressComponentToRecipeValue).not.toHaveProperty('CountryCode');

        });

    });

    describe('getGeolocationComponentToRecipeValueMap', () => {

        test('returns an expression for every compound geolocation component, and only those', () => {

            const geolocationComponentToRecipeValue = fakerJSRecipeFakerService.getGeolocationComponentToRecipeValueMap();

            expect(Object.keys(geolocationComponentToRecipeValue)).toEqual(['Latitude', 'Longitude']);

        });

        test('returns the expected faker-js location expressions', () => {

            const geolocationComponentToRecipeValue = fakerJSRecipeFakerService.getGeolocationComponentToRecipeValueMap();

            expect(geolocationComponentToRecipeValue['Latitude']).toBe('${{faker.location.latitude({ min: -90, max: 90 })}}');
            expect(geolocationComponentToRecipeValue['Longitude']).toBe('${{faker.location.longitude({ min: -180, max: 180 })}}');

        });

        /*
            Asserts the EXPRESSION's bounds rather than a sampled value: a generated coordinate is
            random, so sampling one proves nothing about the range the recipe actually constrains.
        */
        test('constrains latitude to -90..90 and longitude to -180..180 in the expression itself', () => {

            const geolocationComponentToRecipeValue = fakerJSRecipeFakerService.getGeolocationComponentToRecipeValueMap();

            expect(geolocationComponentToRecipeValue['Latitude']).toContain('min: -90');
            expect(geolocationComponentToRecipeValue['Latitude']).toContain('max: 90');
            expect(geolocationComponentToRecipeValue['Longitude']).toContain('min: -180');
            expect(geolocationComponentToRecipeValue['Longitude']).toContain('max: 180');

        });

        /*
            The bounds above are only meaningful if faker still accepts them as options, so the real
            provider is exercised here rather than trusted from the expression text.
        */
        test('the bounded faker calls the expressions name produce coordinates inside those ranges', () => {

            Array.from({ length: 100 }).forEach(() => {

                const generatedLatitude = faker.location.latitude({ min: -90, max: 90 });
                expect(generatedLatitude).toBeGreaterThanOrEqual(-90);
                expect(generatedLatitude).toBeLessThanOrEqual(90);

                const generatedLongitude = faker.location.longitude({ min: -180, max: 180 });
                expect(generatedLongitude).toBeGreaterThanOrEqual(-180);
                expect(generatedLongitude).toBeLessThanOrEqual(180);

            });

        });

    });

    /*
        Event.Location is a plain Text field in the OOTB static map, NOT a Geolocation compound field,
        so the geolocation work must leave its composed street/city/state/zip value exactly as it was.
    */
    describe('Event.Location OOTB mapping', () => {

        test('keeps its composed address value byte-identical', () => {

            const ootbObjectToFieldMappings = fakerJSRecipeFakerService.getOOTBObjectApiNameToFieldApiNameMap();

            expect(ootbObjectToFieldMappings['Event']['Location']).toBe(
                '${{faker.location.streetAddress()}}, {{faker.location.city()}}, {{faker.location.state()}} {{faker.location.zipCode()}}'
            );

        });

    });

});
