import { RecordTypeWrapper } from "../../../RecordTypeService/RecordTypesWrapper";
import { FakerJSRecipeFakerService } from "../FakerJSRecipeFakerService";

describe('FakerJSRecipeFakerService Shared Intstance Tests', () => {

    let fakerJSRecipeFakerService = new FakerJSRecipeFakerService();

    describe('getMapSalesforceFieldToFakerValue', () => {

        const fieldTypeToNPMFakerMappings = fakerJSRecipeFakerService.getMapSalesforceFieldToFakerValue();
        const placeholderForXMLMarkupDependentValue = 'GENERATED BY FIELD XML MARKUP';
        const referenceValuePlaceholder = '### TODO -- REFERENCE ID REQUIRED';
        const seeOnePagerPlaceholder = '### TODO -- SEE ONE PAGER - https://gist.github.com/jdschleicher/4abfd188a933598833285ee76e560445';

        test('Text field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['text']).toBe('${{ faker.lorem.text(5).substring(0, 255) }}');
        });

        test('TextArea field returns correct npm faker expression', () => {

            const textAreaExpression = fieldTypeToNPMFakerMappings['textarea'];
            expect(textAreaExpression).toBe('${{ faker.lorem.paragraph() }}');
            
        });

        test('LongTextArea field returns correct npm faker expression', () => {
            const longTextAreaExpression = fieldTypeToNPMFakerMappings['longtextarea'];
            expect(longTextAreaExpression).toBe('${{ faker.lorem.text(100) }}');
        });

        test('RichTextArea Html field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['html']).toBe('${{ faker.string.alpha(10) }}');
        });

        test('Email field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['email']).toBe('\${{ faker.internet.email() }}');
        });

        test('Phone field returns correct npm faker expression', () => {
            const phoneFakerExpression = fieldTypeToNPMFakerMappings['phone'];
            expect(phoneFakerExpression).toBe(`|
                \${{ faker.phone.number({style:\'national\'}) }}`);
        });

        test('Url field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['url']).toBe('\${{ faker.internet.url() }}');
        });

        test('Number field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['number']).toBe(`|
                \${{ faker.number.int({min: 0, max: 999999}) }}`);
        });

        test('Currency field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['currency']).toBe('\${{ faker.finance.amount(0, 999999, 2) }}');
        });

        test('Percent field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['percent']).toBe(`|
                \${{ faker.number.float({ min: 0, max: 99, precision: 0.01 }).toFixed(2) }}`);
        });

        test('Date field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['date']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'2023-01-01\'), to: new Date() }).toISOString().split(\'T\')[0] }}`);
        });

        test('DateTime field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['datetime']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'2023-01-01T00:00:00Z\'), to: new Date() }).toISOString() }}`);
        });

        test('Time field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['time']).toBe(`|
                \${{ faker.date.between({ from: new Date(\'1970-01-01T00:00:00Z\'), to: new Date(\'1970-01-01T23:59:59Z\') }).toISOString().split(\'T\')[1] }}`);
        });

        test('Picklist field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['picklist']).toBe(placeholderForXMLMarkupDependentValue);
        });

        test('MultiselectPicklist field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['multiselectpicklist']).toBe(placeholderForXMLMarkupDependentValue);
        });

        test('Checkbox field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['checkbox']).toBe('\${{ faker.datatype.boolean() }}');
        });

        test('Lookup field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['lookup']).toBe(referenceValuePlaceholder);
        });

        test('MasterDetail field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['masterdetail']).toBe(referenceValuePlaceholder);
        });

        test('Formula field returns correct message', () => {
            expect(fieldTypeToNPMFakerMappings['formula']).toBe('### TODO - Formula fields are calculated, not generated - remove this line');
        });

        test('Location field returns correct npm faker expression', () => {
            expect(fieldTypeToNPMFakerMappings['location']).toBe(seeOnePagerPlaceholder);
        });

        test('All Salesforce field types have a corresponding mapping', () => {
            const expectedFields = [
                'text', 'textarea', 'longtextarea', 'html', 'email', 
                'phone', 'url', 'number', 'currency', 'percent', 'date', 
                'datetime', 'time', 'picklist', 'multiselectpicklist', 'checkbox', 
                'lookup', 'masterdetail', 'formula', 'location'
            ];

            expectedFields.forEach(field => {
                expect(fieldTypeToNPMFakerMappings).toHaveProperty(field);
            });
        });

        test('All mapping values are strings', () => {
            Object.values(fieldTypeToNPMFakerMappings).forEach(value => {
                expect(typeof value).toBe('string');
            });
        });

    });

    describe('generateTabs', ()=> {

        test('given 1 tab argument, returns expected spaces', () => {

            const expectedTabs = 4; 
            const actualTabResult = fakerJSRecipeFakerService.generateTabs(1);
            const actualSpacesCount = actualTabResult.length;
            expect(actualSpacesCount).toEqual(expectedTabs);

        });

    });

    describe('buildMultiSelectPicklistRecipeValueByXMLFieldDetail', () => {

        test('given expected list of choices, returns expected multiselect picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ (faker.helpers.arrayElements([`apple`,`orange`,`banana`])).join(';') }}";
            const emptyRecordTypeApiToRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildMultiSelectPicklistRecipeValueByXMLFieldDetail(possibleChoices, emptyRecordTypeApiToRecordTypeWrapperMap, fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

    });

    describe('buildDependentPicklistRecipeFakerValue', () => {

        test('given expected controlling value picklist options, returns expected dependent picklist faker value', () => {

            const expectedControllingValueToPicklistOptions: Record<string, string[]> = {
                Toyota: ["Corolla", "Camry", "Prius"],
                Ford: ["F-150", "Mustang", "Explorer"],
                Honda: ["Civic", "Accord", "Pilot"],
                Tesla: ["Model S", "Model 3", "Model X"],
            };            

            const controllingField = "CarBrand__c";
            
            const expectedDependentPicklistRecipeValue =`
      if:
        - choice:
            when: \${{ ${controllingField} == 'Toyota' }}
            pick:
                random_choice:
                    - Corolla
                    - Camry
                    - Prius
        - choice:
            when: \${{ ${controllingField} == 'Ford' }}
            pick:
                random_choice:
                    - F-150
                    - Mustang
                    - Explorer
        - choice:
            when: \${{ ${controllingField} == 'Honda' }}
            pick:
                random_choice:
                    - Civic
                    - Accord
                    - Pilot
        - choice:
            when: \${{ ${controllingField} == 'Tesla' }}
            pick:
                random_choice:
                    - Model S
                    - Model 3
                    - Model X`;


            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "CarModel__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildDependentPicklistRecipeFakerValue(expectedControllingValueToPicklistOptions, 
                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                        controllingField, 
                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedDependentPicklistRecipeValue);
        });

    });

    describe('buildPicklistRecipeValueByXMLFieldDetail', () => {

        test('given expected list of choices, returns expected  picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ faker.helpers.arrayElement([`apple`,`orange`,`banana`]) }}";
            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(possibleChoices, 
                                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

            test('given expected list of choices, returns expected  picklist faker value', () => {

            const possibleChoices: string[] = ['apple', 'orange', 'banana'];
            const expectedRecipeValue = "\${{ faker.helpers.arrayElement([`apple`,`orange`,`banana`]) }}";
            const emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap: Record<string, RecordTypeWrapper> = {};
            const fakeFieldApiName = "Fruit__c";
            const actualFakerValue = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(possibleChoices, 
                                                                        emptyRecordTypeNameByRecordTypeNameToXRecordTypeWrapperMap, 
                                                                        fakeFieldApiName);

            expect(actualFakerValue).toBe(expectedRecipeValue);
        });

    });

    describe('buildTextRecipeValueWithLength — constraint-aware', () => {

        test('given lengthMax constraint smaller than XML length, uses the constraint max', () => {
            const constraints: any[] = [{ constraintType: 'lengthMax', value: 50, fieldApiName: 'Description', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildTextRecipeValueWithLength(255, constraints);
            expect(result).toContain('substring(0, 50)');
        });

        test('given lengthMin constraint, pads generated text to minimum length', () => {
            const constraints: any[] = [{ constraintType: 'lengthMin', value: 10, fieldApiName: 'Description', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildTextRecipeValueWithLength(255, constraints);
            expect(result).toContain('.padEnd(10');
        });

        test('given regex constraint, returns fromRegExp expression', () => {
            const constraints: any[] = [{ constraintType: 'regex', value: '^[0-9]{10}$', fieldApiName: 'Phone', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildTextRecipeValueWithLength(255, constraints);
            expect(result).toContain('faker.helpers.fromRegExp');
            expect(result).toContain('^[0-9]{10}$');
        });

        test('given no constraints, returns default expression', () => {
            const result = fakerJSRecipeFakerService.buildTextRecipeValueWithLength(100);
            expect(result).toContain('substring(0, 100)');
            expect(result).not.toContain('padEnd');
        });

    });

    describe('buildNumericRecipeValueWithPrecisionAndScale — constraint-aware', () => {

        test('given numericMin constraint, uses it as the min value', () => {
            const constraints: any[] = [{ constraintType: 'numericMin', value: 100, fieldApiName: 'Amount', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildNumericRecipeValueWithPrecisionAndScale(10, 0, constraints);
            expect(result).toContain('min: 100');
        });

        test('given numericMax constraint, caps the max at the constraint value', () => {
            const constraints: any[] = [{ constraintType: 'numericMax', value: 500, fieldApiName: 'Amount', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildNumericRecipeValueWithPrecisionAndScale(10, 0, constraints);
            expect(result).toContain('max: 500');
        });

        test('given no constraints, uses 0 as min', () => {
            const result = fakerJSRecipeFakerService.buildNumericRecipeValueWithPrecisionAndScale(6, 0);
            expect(result).toContain('min: 0');
        });

    });

    describe('buildPicklistRecipeValueByXMLFieldDetail — constraint-aware', () => {

        test('given picklistExclude constraint, filters out the excluded value', () => {
            const choices = ['Open', 'Closed', 'Cancelled'];
            const constraints: any[] = [{ constraintType: 'picklistExclude', value: 'Cancelled', fieldApiName: 'Status__c', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(choices, {}, 'Status__c', constraints);
            expect(result).not.toContain('Cancelled');
            expect(result).toContain('Open');
            expect(result).toContain('Closed');
        });

        test('given picklistExclude that removes all choices, falls back to full choices list', () => {
            const choices = ['Only'];
            const constraints: any[] = [{ constraintType: 'picklistExclude', value: 'Only', fieldApiName: 'Status__c', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildPicklistRecipeValueByXMLFieldDetail(choices, {}, 'Status__c', constraints);
            expect(result).toContain('Only');
        });

    });

    describe('buildDateRecipeValue', () => {

        test('given no constraints, returns default date range expression', () => {
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('date');
            expect(result).toContain('faker.date.between');
            expect(result).toContain("new Date('2023-01-01')");
            expect(result).toContain('.toISOString().split(\'T\')[0]');
        });

        test('given dateRelativeMin (TODAY), uses new Date() as from', () => {
            const constraints: any[] = [{ constraintType: 'dateRelativeMin', value: 'TODAY', fieldApiName: 'CloseDate', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('date', constraints);
            expect(result).toContain('from: new Date()');
        });

        test('given dateRelativeMax (TODAY), uses new Date() as to', () => {
            const constraints: any[] = [{ constraintType: 'dateRelativeMax', value: 'TODAY', fieldApiName: 'CloseDate', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('date', constraints);
            expect(result).toContain("to: new Date()");
        });

        test('given dateMin with ISO date, uses it as from', () => {
            const constraints: any[] = [{ constraintType: 'dateMin', value: '2020-01-01', fieldApiName: 'CloseDate', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('date', constraints);
            expect(result).toContain("new Date('2020-01-01')");
        });

        test('given dateMax with ISO date, uses it as to', () => {
            const constraints: any[] = [{ constraintType: 'dateMax', value: '2025-12-31', fieldApiName: 'CloseDate', rawFormula: '', errorMessage: '', ruleName: 'R1' }];
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('date', constraints);
            expect(result).toContain("new Date('2025-12-31')");
        });

        test('given datetime field type, omits the T[0] split', () => {
            const result = fakerJSRecipeFakerService.buildDateRecipeValue('datetime');
            expect(result).toContain('.toISOString()');
            expect(result).not.toContain("split('T')[0]");
        });

    });

    describe('getOOTBExpectedObjectToFakerValueMappings', () => {

        test('given expected list of OOTB object keys, mapping keys are found', () => {
            
            const actualMappings = fakerJSRecipeFakerService.getOOTBObjectApiNameToFieldApiNameMap();

            const expectedObjectsInMappings = [
                'Account',
                'Contact',
                'Opportunity',
                'Lead',
                'Case',
                'Campaign',
                'Task',
                'Event',
                'Product2',
                'PriceBook2',
                'Asset',
                'Contract'
            ];

            expectedObjectsInMappings.forEach(objectName => {
                expect(objectName in actualMappings).toBe(true);
            });

            expect(Object.keys(actualMappings).length).toBe(expectedObjectsInMappings.length);

        });

    });

});