// Guard for what enters the published .vsix, asked for by #67 and added by #121.
//
// #121: ts-node sat in "dependencies" and shipped 1.6 MB to every Marketplace user, because
// nothing between "npm install" and "vsce publish" ever looked at what came out. #67 was the
// same shape one directory up -- Salesforce CLI tooling state under .sfdx/ and .sf/ packaged
// because .vscodeignore did not name it.
//
// A checked-in snapshot of the 2900-path file list would catch both and be regenerated by hand
// on every dependency bump, which makes it a file people update rather than read. So the only
// thing checked in here is the eight top-level names; the dependency half is COMPUTED from the
// compiled output, and therefore needs no maintenance: a genuine runtime dependency is imported
// by construction, and a build-only tool never is.

const fs = require('fs');
const path = require('path');
const { builtinModules } = require('module');

// Every path vsce emits must start with one of these. Salesforce CLI state (.sfdx/, .sf/), the
// design record (docs/), coverage output, workspace scratch (treecipe/) and the TypeScript
// sources are all excluded by .vscodeignore today; this is what notices when one stops being.
const TOP_LEVEL_PATH_ALLOW_LIST = [
    'CHANGELOG.md',
    'LICENSE',
    'README.md',
    'apexPicklistDependencyFramework',
    'images',
    'node_modules',
    'out',
    'package.json'
];

// Provided by the extension host at runtime and never installed, so it is neither a builtin nor
// a declared dependency. It is the one specifier that legitimately satisfies neither check.
const HOST_PROVIDED_MODULES = ['vscode'];

const BARE_REQUIRE_PATTERN = /require\(\s*['"]([^'"]+)['"]\s*\)/g;

class PackagedContentsChecker {

    static parsePackagedPaths(vsceListOutput) {

        return vsceListOutput
            .split('\n')
            .map(listedPath => listedPath.trim())
            .filter(listedPath => listedPath.length > 0)
            .map(listedPath => listedPath.replace(/\\/g, '/'));

    }

    static getTopLevelSegment(packagedPath) {
        return packagedPath.split('/')[0];
    }

    static collectTopLevelPathViolations(packagedPaths, allowedTopLevelPaths = TOP_LEVEL_PATH_ALLOW_LIST) {

        const allowed = new Set(allowedTopLevelPaths);
        const exampleByUnexpectedSegment = new Map();

        for (const packagedPath of packagedPaths) {
            const topLevelSegment = this.getTopLevelSegment(packagedPath);
            if (!allowed.has(topLevelSegment) && !exampleByUnexpectedSegment.has(topLevelSegment)) {
                exampleByUnexpectedSegment.set(topLevelSegment, packagedPath);
            }
        }

        // The segment alone can be degenerate -- an absolute path yields "" and "./out/x.js"
        // yields "." -- so the first path that produced it is named too, or the message tells a
        // reader nothing about what to exclude.
        return [...exampleByUnexpectedSegment.keys()].sort().map(segment =>
            `Unexpected top-level path "${segment}" is in the package `
            + `(first seen as "${exampleByUnexpectedSegment.get(segment)}"). `
            + `Exclude it in .vscodeignore, or add it to TOP_LEVEL_PATH_ALLOW_LIST if it is meant to ship.`
        );

    }

    // Only files the package actually carries are scanned. out/**/tests/** is excluded by
    // .vscodeignore, which is why the jest-extended requires under it are not a runtime leak --
    // reading them off disk instead of off this list would report one that does not exist.
    static collectScannablePackagedSourcePaths(packagedPaths) {

        return packagedPaths.filter(packagedPath =>
            !packagedPath.startsWith('node_modules/') && packagedPath.endsWith('.js')
        );

    }

    // A require named only in a COMMENT is the failure that matters: it would keep assertion 2
    // green for a dependency nothing loads, which is precisely how #121 stayed hidden. Block
    // comments and whole-line "//" comments are removed; a trailing "//" is deliberately NOT,
    // because a "//" inside a string ("https://...") would truncate the rest of a real line and
    // turn a false positive into a false negative -- the worse direction. A require written
    // inside a STRING LITERAL is therefore still counted; that is a known limitation, pinned by
    // a spec rather than left to be rediscovered.
    static stripComments(javascriptSource) {

        return javascriptSource
            .replace(/\/\*[\s\S]*?\*\//g, '')
            .split('\n')
            .filter(line => !line.trimStart().startsWith('//'))
            .join('\n');

    }

    static collectBareModuleSpecifiers(javascriptSource) {

        const specifiers = new Set();
        const scannableSource = this.stripComments(javascriptSource);
        let match;

        BARE_REQUIRE_PATTERN.lastIndex = 0;
        while ((match = BARE_REQUIRE_PATTERN.exec(scannableSource)) !== null) {
            const specifier = match[1];
            if (!specifier.startsWith('.') && !specifier.startsWith('/')) {
                specifiers.add(specifier);
            }
        }

        return [...specifiers].sort();

    }

    // "@salesforce/core/lib/thing" and "js-yaml/dist" name the packages "@salesforce/core" and
    // "js-yaml"; a deep import is still that dependency being used.
    static toPackageName(moduleSpecifier) {

        const withoutNodePrefix = moduleSpecifier.replace(/^node:/, '');
        const segments = withoutNodePrefix.split('/');

        if (withoutNodePrefix.startsWith('@')) {
            return segments.slice(0, 2).join('/');
        }

        return segments[0];

    }

    static isNodeBuiltinModule(moduleSpecifier) {
        return builtinModules.includes(moduleSpecifier.replace(/^node:/, ''));
    }

    static collectRequiredPackageNames(packagedSourcePaths, readPackagedSource) {

        const requiredPackageNames = new Set();

        for (const sourcePath of packagedSourcePaths) {
            for (const specifier of this.collectBareModuleSpecifiers(readPackagedSource(sourcePath))) {
                if (!this.isNodeBuiltinModule(specifier)) {
                    requiredPackageNames.add(this.toPackageName(specifier));
                }
            }
        }

        return requiredPackageNames;

    }

    // The assertion #121 is about. A dependency nothing requires is a dependency the user
    // downloads and never runs.
    static collectUnusedRuntimeDependencyViolations(declaredDependencyNames, requiredPackageNames) {

        return declaredDependencyNames
            .filter(dependencyName => !requiredPackageNames.has(dependencyName))
            .sort()
            .map(dependencyName =>
                `"${dependencyName}" is declared in dependencies but is never required from any `
                + `packaged out/** file. Move it to devDependencies.`
            );

    }

    // The other direction: shipped code reaching for something only devDependencies install
    // resolves on a contributor's machine and throws on a user's.
    static collectUndeclaredRuntimeRequireViolations(requiredPackageNames, declaredDependencyNames) {

        const declared = new Set([...declaredDependencyNames, ...HOST_PROVIDED_MODULES]);

        return [...requiredPackageNames]
            .filter(packageName => !declared.has(packageName))
            .sort()
            .map(packageName =>
                `Packaged code requires "${packageName}", which is not declared in dependencies. `
                + `A devDependency does not ship, so this throws for an installed user.`
            );

    }

    static checkPackagedContents({ packagedPaths, declaredDependencyNames, readPackagedSource }) {

        const packagedSourcePaths = this.collectScannablePackagedSourcePaths(packagedPaths);
        const requiredPackageNames = this.collectRequiredPackageNames(packagedSourcePaths, readPackagedSource);

        return [
            ...this.collectTopLevelPathViolations(packagedPaths),
            ...this.collectUnusedRuntimeDependencyViolations(declaredDependencyNames, requiredPackageNames),
            ...this.collectUndeclaredRuntimeRequireViolations(requiredPackageNames, declaredDependencyNames)
        ];

    }

    // Same containment discipline the extension applies to any manifest path it opens
    // (CLAUDE.md: resolveOpenableManifestFilePath / isPathContainedInWorkspace). "vsce ls" never
    // emits a "..", but the reader accepts a path from a FILE, and a reader that resolves outside
    // the directory it was pointed at is the property worth keeping rather than the current
    // absence of a producer that would exercise it. readFileSync also follows symlinks, which
    // "vsce ls" lists as plain files, so the resolved real path is what gets checked.
    static resolveContainedWorkspacePath(workspaceDirectoryPath, packagedPath) {

        if (path.isAbsolute(packagedPath)) {
            return null;
        }

        const workspaceRoot = this.getRealDirectoryPath(workspaceDirectoryPath);
        const resolvedPath = this.getRealDirectoryPath(path.resolve(workspaceRoot, packagedPath));

        const isContained = resolvedPath === workspaceRoot
            || resolvedPath.startsWith(workspaceRoot + path.sep);

        return isContained ? resolvedPath : null;

    }

    // Resolves what exists and falls back to the lexical path for what does not, so a listed but
    // missing file is reported as missing rather than as an escape.
    static getRealDirectoryPath(candidatePath) {

        try {
            return fs.realpathSync(candidatePath);
        } catch (error) {
            return path.resolve(candidatePath);
        }

    }

    static runAgainstWorkspace(vsceListFilePath, workspaceDirectoryPath) {

        let vsceListContents;
        try {
            vsceListContents = fs.readFileSync(vsceListFilePath, 'utf8');
        } catch (error) {
            return [`Could not read the packaged listing "${vsceListFilePath}": ${error.message}`];
        }

        const packagedPaths = this.parsePackagedPaths(vsceListContents);

        if (packagedPaths.length === 0) {
            return [`"${vsceListFilePath}" lists no packaged paths. Did "vsce ls" run?`];
        }

        let extensionManifest;
        const manifestPath = path.join(workspaceDirectoryPath, 'package.json');
        try {
            extensionManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
        } catch (error) {
            return [`Could not read "${manifestPath}": ${error.message}`];
        }

        const escapedPaths = [];
        const unreadablePaths = [];

        const readPackagedSource = packagedPath => {

            const containedPath = this.resolveContainedWorkspacePath(workspaceDirectoryPath, packagedPath);

            if (containedPath === null) {
                escapedPaths.push(packagedPath);
                return '';
            }

            try {
                return fs.readFileSync(containedPath, 'utf8');
            } catch (error) {
                unreadablePaths.push(`${packagedPath}: ${error.message}`);
                return '';
            }

        };

        const violations = this.checkPackagedContents({
            packagedPaths,
            declaredDependencyNames: Object.keys(extensionManifest.dependencies || {}),
            readPackagedSource
        });

        // Reported ahead of the assertions: a file that was not read cannot have contributed its
        // requires, so assertion 2 would blame the dependency rather than the unread file.
        return [
            ...escapedPaths.map(packagedPath =>
                `Packaged path "${packagedPath}" resolves outside the workspace and was not read.`
            ),
            ...unreadablePaths.map(detail => `Packaged path could not be read -- ${detail}`),
            ...violations
        ];

    }

    // The command line entry point returns its exit code rather than calling process.exit, so the
    // failure path CI depends on is exercised by a test rather than by trusting CI to fail one day.
    static main(commandLineArguments, workspaceDirectoryPath, consoleOutput = console) {

        const vsceListFilePath = commandLineArguments[2];

        if (!vsceListFilePath) {
            consoleOutput.error('Usage: node checkPackagedPaths.js <vsce-ls-output-file>');
            return 1;
        }

        const violations = this.runAgainstWorkspace(vsceListFilePath, workspaceDirectoryPath);

        if (violations.length > 0) {
            consoleOutput.error('Package contents check FAILED:');
            violations.forEach(violation => consoleOutput.error(`  - ${violation}`));
            return 1;
        }

        consoleOutput.log('Package contents check passed.');
        return 0;

    }

}

module.exports = { PackagedContentsChecker, TOP_LEVEL_PATH_ALLOW_LIST, HOST_PROVIDED_MODULES };

if (require.main === module) {
    process.exit(PackagedContentsChecker.main(process.argv, process.cwd()));
}
