

import { RecordTypeWrapper } from "../../RecordTypeService/RecordTypesWrapper";
import { IRecipeFakerService } from "../IRecipeFakerService";
import { ValidationRuleConstraint } from "../../ValidationRuleAnalyzerService/ValidationRuleAnalyzerService";

export class SnowfakeryRecipeFakerService implements IRecipeFakerService {

    openingRecipeSyntax:string = "${{";
    closingRecipeSyntax:string = "}}";

    generateTabs(tabCount: number):string {
        const spacesPerTab = 4;
        return ' '.repeat(spacesPerTab * tabCount);
    }

    getMapSalesforceFieldToFakerValue():Record<string, string> {

        const salesforceFieldToSnowfakeryMap: Record<string, string> = {
            'text': '${{fake.text(max_nb_chars=50)}}',
            'textarea': '${{fake.paragraph()}}',
            'longtextarea': '${{fake.text(max_nb_chars=1000)}}',
            'html': '${{fake.text(max_nb_chars=1000)}}',
            'email': '${{fake.email()}}',
            'phone': '${{fake.phone_number()}}',
            'url': '${{fake.url()}}',
            'number': '${{fake.random_int(min=0, max=999999)}}',
            'currency': '${{fake.pydecimal(left_digits=6, right_digits=2, positive=True)}}',
            'percent': '${{fake.pydecimal(left_digits=2, right_digits=2, positive=True)}}',
            'date': '${{date(fake.date_between(start_date="-1y", end_date="today"))}}',
            'datetime': '${{ (fake.date_time_between(start_date="-1y", end_date="now")).strftime("%Y-%m-%dT%H:%M:%S.000+0000") }}',
            'time': '${{fake.time()}}',
            'picklist': 'GENERATED BY FIELD XML MARKUP',
            'multiselectpicklist': 'GENERATED BY FIELD XML MARKUP',
            'checkbox': '${{ (random_choice("true", "false")).lower() }}',
            'lookup': '### TODO -- REFERENCE ID REQUIRED',
            'masterdetail': '### TODO -- REFERENCE ID REQUIRED',
            'formula': '### TODO - REMOVE ME - Formula fields are calculated, not generated',
            'location': '### TODO -- SEE ONE PAGER - https://gist.github.com/jdschleicher/4abfd188a933598833285ee76e560445'
        };
    
        return salesforceFieldToSnowfakeryMap;

    }

    buildMultiSelectPicklistRecipeValueByXMLFieldDetail(availablePicklistChoices: string[],
                                                        recordTypeNameByRecordTypeWrapper: Record<string, RecordTypeWrapper>,
                                                        associatedFieldApiName
                                                        ): string {

        const commaJoinedPicklistChoices = availablePicklistChoices.join("', '");
        let fakeMultiSelectRecipeValue = `${this.openingRecipeSyntax} (';').join((fake.random_sample(elements=('${commaJoinedPicklistChoices}')))) ${this.closingRecipeSyntax}`;
        
        const recordTypeBasedRecipeValues = this.buildRecordTypeBasedMultipicklistRecipeValue(recordTypeNameByRecordTypeWrapper, associatedFieldApiName);
        if ( recordTypeBasedRecipeValues) {
            fakeMultiSelectRecipeValue += `\n${recordTypeBasedRecipeValues}`;
        }
        
        return fakeMultiSelectRecipeValue;

    }

    buildDependentPicklistRecipeFakerValue(
                        controllingValueToPicklistOptions: Record<string, string[]>, 
                        recordTypeApiToRecordTypeWrapperMap: Record<string, RecordTypeWrapper>,
                        controllingField: string,
                        fieldApiName: string
                    ): string {
    
        let allDependentPicklistChoiceRecipe:string;

        const newLineBreak = `\n`;

        for ( const controllingValueKey in controllingValueToPicklistOptions ) {
            
            let randomChoicesBreakdown:string;

            let picklistValuesAvailableForChoice = controllingValueToPicklistOptions[controllingValueKey];
            // get initial list of all available picklist values before record type sections
            picklistValuesAvailableForChoice.forEach( value => {

                if (randomChoicesBreakdown) {
                    randomChoicesBreakdown += `${newLineBreak}${this.generateTabs(5)}- ${value}`;
                } else {
                    randomChoicesBreakdown = `- ${value}`;
                }

            });   

            const allRecordTypeChoicesBreakdown = this.updateDependentPicklistRecipeFakerValueByRecordTypeSections( 
                                                        recordTypeApiToRecordTypeWrapperMap, 
                                                        fieldApiName, 
                                                        controllingField,
                                                        controllingValueKey
                                                    );

            if (allRecordTypeChoicesBreakdown) {
                randomChoicesBreakdown += allRecordTypeChoicesBreakdown;
            }

            let dependentPicklistRandomChoiceRecipe = 
`${this.generateTabs(2)}- choice:
${this.generateTabs(3)}when: ${this.openingRecipeSyntax} ${controllingField} == '${controllingValueKey}' }}
${this.generateTabs(3)}pick:
${this.generateTabs(4)}random_choice:
${this.generateTabs(5)}${randomChoicesBreakdown}`;

            if (!(allDependentPicklistChoiceRecipe)) {
                allDependentPicklistChoiceRecipe = dependentPicklistRandomChoiceRecipe;
            } else {
                const lineBreakRandomChoiceRecipe = `\n${dependentPicklistRandomChoiceRecipe}`;
                allDependentPicklistChoiceRecipe += lineBreakRandomChoiceRecipe;
            }

        }

        let fakeDependentPicklistRecipeValue = "";

        if (fakeDependentPicklistRecipeValue) {
            fakeDependentPicklistRecipeValue += `\n${this.generateTabs(2)}${allDependentPicklistChoiceRecipe}`;
        } else {
            fakeDependentPicklistRecipeValue = `\n${this.generateTabs(1.5)}if:`;
            fakeDependentPicklistRecipeValue += `\n${allDependentPicklistChoiceRecipe}`;
        }

        return fakeDependentPicklistRecipeValue;

    }

      buildPicklistRecipeValueByXMLFieldDetail(availablePicklistChoices: string[],
                                                recordTypeNameByRecordTypeWrapper: Record<string, RecordTypeWrapper>,
                                                fieldApiName: string,
                                                constraints: ValidationRuleConstraint[] = []): string {

        let fakeRecipeValue = '';

        if ( !(availablePicklistChoices) || availablePicklistChoices.length === 0 ) {
            // indicates no svs or picklistvlaues
            return "### TODO: This picklist field needs manually updated with either a standard value set list or global value set";
        }

        const excludedValues = constraints
            .filter(c => c.constraintType === 'picklistExclude')
            .map(c => c.value as string);
        const filteredChoices = excludedValues.length > 0
            ? availablePicklistChoices.filter(choice => !excludedValues.includes(choice))
            : availablePicklistChoices;
        const choicesToUse = filteredChoices.length > 0 ? filteredChoices : availablePicklistChoices;

        const commaJoinedPicklistChoices = choicesToUse.join("', '");
        fakeRecipeValue = `${this.openingRecipeSyntax} random_choice('${commaJoinedPicklistChoices}') ${this.closingRecipeSyntax}`;

        const recordTypeBasedRecipeValues = this.buildRecordTypeBasedPicklistRecipeValue(recordTypeNameByRecordTypeWrapper, fieldApiName);
        if ( recordTypeBasedRecipeValues) {
            fakeRecipeValue += `\n${recordTypeBasedRecipeValues}`;
        }

        return fakeRecipeValue;

    }

    updateDependentPicklistRecipeFakerValueByRecordTypeSections(recordTypeNameByRecordTypeWrapper: Record<string, RecordTypeWrapper>,
                                                                dependentFieldApiName: string,
                                                                controllingFieldApiName: string,
                                                                controllingValue: string
                                                            ): string {

        const newLineBreak: string = `\n`;
        let allRecordTypeChoicesBreakdown:string = '';    
                                                        
        Object.entries(recordTypeNameByRecordTypeWrapper).forEach(([recordTypeApiNameKey, recordTypeWrapper]) => {
                
            const availableRecordTypePicklistValuesForControllingField = recordTypeWrapper.PicklistFieldSectionsToPicklistDetail[controllingFieldApiName];

            const noPicklistValuesForRecordTypeVerbiage = `${newLineBreak}${this.generateTabs(5)}### TODO: -- RecordType Options -- ${recordTypeApiNameKey} -- "${controllingValue}" is not an available value for ${controllingFieldApiName} for record type ${recordTypeApiNameKey}`;

            if ( !availableRecordTypePicklistValuesForControllingField || !availableRecordTypePicklistValuesForControllingField.includes(controllingValue) ) {
  
                /*
                    EITHER
                     - picklist value not available for record type so no dependent picklist values to process
                     - controlling api field doesn't exist in record type markup so no dependent picklist values to process
                */
                allRecordTypeChoicesBreakdown += noPicklistValuesForRecordTypeVerbiage;
                
            } else {

                let recordTypeChoicesBreakdown:string;

                const picklistValuesForDependentField = recordTypeWrapper.PicklistFieldSectionsToPicklistDetail[dependentFieldApiName];
                picklistValuesForDependentField.forEach( recordTypeAvailablePicklistValue => {
    
                    if (recordTypeChoicesBreakdown) {
                        recordTypeChoicesBreakdown += `${newLineBreak}${this.generateTabs(5)}- ${recordTypeAvailablePicklistValue}`;
                    } else {
                        const recordTypeTodoVerbiage = `### TODO: -- RecordType Options -- ${recordTypeApiNameKey} -- SELECT THIS SECTION OF OPTIONS IF USING RECORD TYPE -- ${recordTypeApiNameKey}`;
                        recordTypeChoicesBreakdown = `${newLineBreak}${this.generateTabs(5)}${recordTypeTodoVerbiage}${newLineBreak}${this.generateTabs(5)}- ${recordTypeAvailablePicklistValue}`;                                
                    }
    
                });
    
                allRecordTypeChoicesBreakdown += recordTypeChoicesBreakdown;
            }

        });

        return allRecordTypeChoicesBreakdown;

    }

    buildRecordTypeBasedPicklistRecipeValue(recordTypeNameByRecordTypeWrapper: Record<string, RecordTypeWrapper>,
                                            associatedFieldApiName: string) {

        let allRecordTypeBasedPicklistOptions:string = '';
        const newLineBreak = `\n`;

        Object.entries(recordTypeNameByRecordTypeWrapper).forEach(([recordTypeApiNameKey, recordTypeWrapper]) => {

            const availableRecordTypePicklistValuesForField = recordTypeWrapper.PicklistFieldSectionsToPicklistDetail[associatedFieldApiName];
            if ( availableRecordTypePicklistValuesForField ) {

                const commaJoinedPicklistChoices = availableRecordTypePicklistValuesForField.join("', '");
                const recordTypBasedFakeRecipeValue = `${this.openingRecipeSyntax} random_choice('${commaJoinedPicklistChoices}') ${this.closingRecipeSyntax}`;
    
                let recordTypeTodoVerbiage = `${this.generateTabs(5)}### TODO: -- RecordType Options -- ${recordTypeApiNameKey} -- Below is the faker recipe for the record type ${recordTypeApiNameKey} for the field ${associatedFieldApiName}`;
                recordTypeTodoVerbiage += `${newLineBreak}${this.generateTabs(5)}${recordTypBasedFakeRecipeValue}`;
                
                if ( allRecordTypeBasedPicklistOptions.trim() === '' ) {
                    // check to see if allRecordTypeBasedPicklistOptions has been given an initial value to properly handle recipe spacing
                    allRecordTypeBasedPicklistOptions = `${recordTypeTodoVerbiage}`;
                } else {
                    allRecordTypeBasedPicklistOptions += `${newLineBreak}${recordTypeTodoVerbiage}`;
                }
    
            }
            
        });

        return allRecordTypeBasedPicklistOptions;

    }

    buildRecordTypeBasedMultipicklistRecipeValue(recordTypeNameByRecordTypeWrapper: Record<string, RecordTypeWrapper>,
                                                    associatedFieldApiName: string) {


        let allRecordTypeBasedMultiselectPicklistOptions:string = '';
        const newLineBreak = `\n`;

        Object.entries(recordTypeNameByRecordTypeWrapper).forEach(([recordTypeApiNameKey, recordTypeWrapper]) => {

            const availableRecordTypePicklistValuesForField = recordTypeWrapper.PicklistFieldSectionsToPicklistDetail[associatedFieldApiName];
            if ( availableRecordTypePicklistValuesForField ) {

                const commaJoinedPicklistChoices = availableRecordTypePicklistValuesForField.join("', '");
                const recordTypBasedFakeRecipeValue = `${this.openingRecipeSyntax} (';').join((fake.random_sample(elements=('${commaJoinedPicklistChoices}')))) ${this.closingRecipeSyntax}`;
                
                let recordTypeTodoVerbiage = `${this.generateTabs(5)}### TODO: -- RecordType Options -- ${recordTypeApiNameKey} -- Below is the Multiselect faker recipe for the record type ${recordTypeApiNameKey} for the field ${associatedFieldApiName}`;
                recordTypeTodoVerbiage += `${newLineBreak}${this.generateTabs(5)}${recordTypBasedFakeRecipeValue}`;
                
                if ( allRecordTypeBasedMultiselectPicklistOptions.trim() === '' ) {
                    // check to see if allRecordTypeBasedPicklistOptions has been given an initial value to properly handle recipe spacing
                    allRecordTypeBasedMultiselectPicklistOptions = `${recordTypeTodoVerbiage}`;
                } else {
                    allRecordTypeBasedMultiselectPicklistOptions += `${newLineBreak}${recordTypeTodoVerbiage}`;
                }
    
            }

        });

        return allRecordTypeBasedMultiselectPicklistOptions;
    }

    getOOTBObjectApiNameToFieldApiNameMap(): Record<string, Record<string, string>> {

        const salesforceSnowfakeryMappings: Record<string, Record<string, string>> = {
            
            "Account": {
              "Name": "${{fake.company}}",
              "AnnualRevenue": "${{random_number(1000000,9999999)}}.00",
              "BillingStreet": "${{fake.street_address}}",
              "BillingCity": "${{fake.city}}",
              "BillingState": "${{fake.state}}",
              "BillingPostalCode": "${{fake.zipcode}}",
              "BillingCountry": "${{fake.country}}",
              "Description": "${{fake.catch_phrase}}",
              "Industry": "${{random_choice('Technology', 'Finance', 'Healthcare', 'Retail', 'Manufacturing', 'Education')}}",
              "NumberOfEmployees": "${{random_number(1000,9999)}}",
              "Phone": "${{fake.phone_number}}",
              "Rating": "${{random_choice('Hot', 'Warm', 'Cold')}}",
              "ShippingStreet": "${{fake.street_address}}",
              "ShippingCity": "${{fake.city}}",
              "ShippingState": "${{fake.state}}",
              "ShippingPostalCode": "${{fake.zipcode}}",
              "ShippingCountry": "${{fake.country}}",
              "Type": "${{random_choice('Customer', 'Partner', 'Prospect')}}",
              "Website": "${{fake.domain_name}}"
            },
            
            "Contact": {
              "FirstName": "${{fake.first_name}}",
              "LastName": "${{fake.last_name}}",
              "Email": "${{fake.email}}",
              "Phone": "${{fake.phone_number}}",
              "MobilePhone": "${{fake.phone_number}}",
              "Title": "${{fake.job}}",
              "Department": "${{random_choice('Sales', 'Marketing', 'IT', 'Finance', 'HR', 'Operations')}}",
              "Birthdate": "${{fake.date_of_birth}}",
              "Description": "${{fake.paragraph}}",
              "MailingStreet": "${{fake.street_address}}",
              "MailingCity": "${{fake.city}}",
              "MailingState": "${{fake.state}}",
              "MailingPostalCode": "${{fake.zipcode}}",
              "MailingCountry": "${{fake.country}}",
              "OtherStreet": "${{fake.street_address}}",
              "OtherCity": "${{fake.city}}",
              "OtherState": "${{fake.state}}",
              "OtherPostalCode": "${{fake.zipcode}}",
              "OtherCountry": "${{fake.country}}",
              "LeadSource": "${{random_choice('Web', 'Phone Inquiry', 'Partner', 'Purchased List', 'Other')}}",
              "Salutation": "${{random_choice('Mr.', 'Ms.', 'Mrs.', 'Dr.')}}",
              "AssistantName": "${{fake.name}}",
              "AssistantPhone": "${{fake.phone_number}}"
            },
            
            "Opportunity": {
              "Name": "${{fake.catch_phrase}}",
              "Amount": "${{random_number(100000,999999)}}.00",
              "CloseDate": "${{date_between(start_date='-30d', end_date='+90d')}}",
              "Description": "${{fake.paragraph}}",
              "LeadSource": "${{random_choice('Web', 'Phone Inquiry', 'Partner', 'Purchased List', 'Other')}}",
              "NextStep": "${{fake.sentence}}",
              "Probability": "${{random_number(10,99)}}.0",
              "StageName": "${{random_choice('Prospecting', 'Qualification', 'Needs Analysis', 'Value Proposition', 'Id. Decision Makers', 'Perception Analysis', 'Proposal/Price Quote', 'Negotiation/Review', 'Closed Won', 'Closed Lost')}}",
              "Type": "${{random_choice('New Customer', 'Existing Customer - Upgrade', 'Existing Customer - Replacement', 'Existing Customer - Downgrade')}}"
            },
            
            "Lead": {
              "FirstName": "${{fake.first_name}}",
              "LastName": "${{fake.last_name}}",
              "Company": "${{fake.company}}",
              "Title": "${{fake.job}}",
              "Email": "${{fake.email}}",
              "Phone": "${{fake.phone_number}}",
              "MobilePhone": "${{fake.phone_number}}",
              "Street": "${{fake.street_address}}",
              "City": "${{fake.city}}",
              "State": "${{fake.state}}",
              "PostalCode": "${{fake.zipcode}}",
              "Country": "${{fake.country}}",
              "Industry": "${{random_choice('Technology', 'Finance', 'Healthcare', 'Retail', 'Manufacturing', 'Education')}}",
              "AnnualRevenue": "${{random_number(1000000,9999999)}}",
              "Description": "${{fake.paragraph}}",
              "LeadSource": "${{random_choice('Web', 'Phone Inquiry', 'Partner', 'Purchased List', 'Other')}}",
              "Rating": "${{random_choice('Hot', 'Warm', 'Cold')}}",
              "Status": "${{random_choice('Open - Not Contacted', 'Working - Contacted', 'Closed - Converted', 'Closed - Not Converted')}}",
              "NumberOfEmployees": "${{random_number(1000,9999)}}"
            },
            
            "Case": {
              "Subject": "${{fake.catch_phrase}}",
              "Description": "${{fake.paragraph}}",
              "Status": "${{random_choice('New', 'Working', 'Escalated', 'Closed')}}",
              "Origin": "${{random_choice('Email', 'Phone', 'Web', 'Social')}}",
              "Priority": "${{random_choice('High', 'Medium', 'Low')}}",
              "Type": "${{random_choice('Problem', 'Feature Request', 'Question')}}",
              "Reason": "${{random_choice('Installation', 'Equipment Complexity', 'Performance', 'Breakdown', 'Equipment Design', 'Feedback')}}",
              "SuppliedName": "${{fake.name}}",
              "SuppliedEmail": "${{fake.email}}",
              "SuppliedPhone": "${{fake.phone_number}}",
              "SuppliedCompany": "${{fake.company}}"
            },
            
            "Product2": {
              "Name": "${{fake.catch_phrase}}",
              "Description": "${{fake.bs}}",
              "ProductCode": "${{fake.ean}}",
              "IsActive": "${{random_choice('true', 'false')}}",
              "Family": "${{random_choice('Hardware', 'Software', 'Services', 'Other')}}",
              "QuantityUnitOfMeasure": "${{random_choice('Each', 'Case', 'Box', 'Pallet')}}",
              "DisplayUrl": "${{fake.url}}",
              "ExternalId": "${{fake.uuid4}}"
            },
            
            "Pricebook2": {
              "Name": "${{fake.bs}} Price Book",
              "Description": "${{fake.paragraph}}",
              "IsActive": "${{random_choice('true', 'false')}}"
            }
            
          };


        return salesforceSnowfakeryMappings;

    }

     getStandardAndGlobalValueSetTODOPlaceholderWithExample():string {

        const emptyPicklistXMLDetailRecipePlaceholder = `### TODO: POSSIBLE GLOBAL OR STANDARD VALUE SET USED FOR THIS PICKLIST AS DETAILS ARE NOT IN FIELD XML MARKUP -- FIND ASSOCIATED VALUE SET AND REPALCE COMMA SEPARATED FRUITS WITH VALUE SET OPTIONS: \${{ random_choice('apple', 'orange', 'banana') }}`;
        return emptyPicklistXMLDetailRecipePlaceholder;

    }

    getMultipicklistTODOPlaceholderWithExample():string {

        const emptyMultiSelectXMLDetailPlaceholder = `### TODO: POSSIBLE GLOBAL OR STANDARD VALUE SET USED FOR THIS MULTIPICKLIST AS DETAILS ARE NOT IN FIELD XML MARKUP -- FIND ASSOCIATED VALUE SET AND REPLACE COMMA SEPARATED FRUITS WITH VALUE SET OPTIONS: \${{ (';').join((fake.random_sample(elements=('apple', 'orange', 'banana')))) }}`;
        return emptyMultiSelectXMLDetailPlaceholder;

    }

    buildTextRecipeValueWithLength(length: number, constraints: ValidationRuleConstraint[] = []): string {

        const regexConstraint = constraints.find(c => c.constraintType === 'regex');
        if (regexConstraint) {
            return `### TODO: Regex constraint "${regexConstraint.value}" from rule "${regexConstraint.ruleName}" — replace with a valid Snowfakery expression`;
        }

        const lenMaxConstraint = constraints.find(c => c.constraintType === 'lengthMax');
        const lenMinConstraint = constraints.find(c => c.constraintType === 'lengthMin');
        const effectiveMax = lenMaxConstraint ? Math.min(Number(lenMaxConstraint.value), length) : length;
        const effectiveMin = lenMinConstraint ? Number(lenMinConstraint.value) : 0;

        if (effectiveMin > 0) {
            return `${this.openingRecipeSyntax}fake.pystr(min_chars=${effectiveMin}, max_chars=${effectiveMax})${this.closingRecipeSyntax}`;
        }

        return `${this.openingRecipeSyntax}fake.text(max_nb_chars=${effectiveMax})${this.closingRecipeSyntax}`;

    }

    buildNumericRecipeValueWithPrecisionAndScale(precision: number, scale?: number, constraints: ValidationRuleConstraint[] = []): string {

        const effectiveScale = scale ?? 0;
        const maxNumbersLeftOfDecimal = '9'.repeat(precision - effectiveScale);

        const minConstraints = constraints.filter(c => c.constraintType === 'numericMin');
        const maxConstraints = constraints.filter(c => c.constraintType === 'numericMax');
        const effectiveMin = minConstraints.length > 0 ? Math.max(...minConstraints.map(c => Number(c.value))) : 0;
        const effectiveMax = maxConstraints.length > 0
            ? Math.min(...maxConstraints.map(c => Number(c.value)), Number(maxNumbersLeftOfDecimal))
            : maxNumbersLeftOfDecimal;

        if (effectiveScale === 0) {
            return `${this.openingRecipeSyntax}fake.random_int(min=${effectiveMin}, max=${effectiveMax})${this.closingRecipeSyntax}`;
        } else {
            const leftDigits = String(effectiveMax).split('.')[0].length;
            return `${this.openingRecipeSyntax}fake.pydecimal(left_digits=${leftDigits}, right_digits=${effectiveScale}, positive=True, min_value=${effectiveMin}, max_value=${effectiveMax})${this.closingRecipeSyntax}`;
        }

    }

    buildCurrencyRecipeValueWithPrecisionAndScale(precision: number, scale?: number, constraints: ValidationRuleConstraint[] = []): string {

        const effectiveScale = scale ?? 0;
        const leftDigitsFromPrecision = precision - effectiveScale;

        const minConstraints = constraints.filter(c => c.constraintType === 'numericMin');
        const maxConstraints = constraints.filter(c => c.constraintType === 'numericMax');

        if (minConstraints.length === 0 && maxConstraints.length === 0) {
            return `${this.openingRecipeSyntax}fake.pydecimal(left_digits=${leftDigitsFromPrecision}, right_digits=${effectiveScale}, positive=True)${this.closingRecipeSyntax}`;
        }

        const maxNumbersLeftOfDecimal = '9'.repeat(leftDigitsFromPrecision);
        const effectiveMin = minConstraints.length > 0 ? Math.max(...minConstraints.map(c => Number(c.value))) : 0;
        const effectiveMax = maxConstraints.length > 0
            ? Math.min(...maxConstraints.map(c => Number(c.value)), Number(maxNumbersLeftOfDecimal))
            : maxNumbersLeftOfDecimal;
        const leftDigits = String(effectiveMax).split('.')[0].length;
        return `${this.openingRecipeSyntax}fake.pydecimal(left_digits=${leftDigits}, right_digits=${effectiveScale}, positive=True, min_value=${effectiveMin}, max_value=${effectiveMax})${this.closingRecipeSyntax}`;

    }

    buildDateRecipeValue(fieldType: string, constraints: ValidationRuleConstraint[] = []): string {

        const relMinConstraint = constraints.find(c => c.constraintType === 'dateRelativeMin');
        const relMaxConstraint = constraints.find(c => c.constraintType === 'dateRelativeMax');
        const absMinConstraint = constraints.find(c => c.constraintType === 'dateMin');
        const absMaxConstraint = constraints.find(c => c.constraintType === 'dateMax');

        const startDate = absMinConstraint
            ? `"${absMinConstraint.value}"`
            : relMinConstraint
                ? `"today"`
                : `"-1y"`;

        const isDate = fieldType.toLowerCase() === 'date';
        const defaultEndDate = isDate ? `"today"` : `"now"`;
        const endDate = absMaxConstraint
            ? `"${absMaxConstraint.value}"`
            : relMaxConstraint
                ? `"today"`
                : defaultEndDate;

        if (isDate) {
            return `${this.openingRecipeSyntax}date(fake.date_between(start_date=${startDate}, end_date=${endDate}))${this.closingRecipeSyntax}`;
        } else {
            return `${this.openingRecipeSyntax} (fake.date_time_between(start_date=${startDate}, end_date=${endDate})).strftime("%Y-%m-%dT%H:%M:%S.000+0000") ${this.closingRecipeSyntax}`;
        }

    }

}

