name: Run JESTS on PUSH

on:
  push:
  pull_request:

jobs:
  
  Compile-and-Test-Salesforce-Data-Treecipe:

    runs-on: ubuntu-latest

    steps:

    - name: Check if PR is a draft (PowerShell)
      id: check_draft
      shell: pwsh
      run: |
        if ($env:GITHUB_EVENT_PULL_REQUEST_DRAFT -eq 'true') {
          Write-Host "This is a draft PR. Skipping the workflow."
          exit 0  # Exit early to skip the rest of the job
        } else {
          Write-Host "This is not a draft PR. Proceeding with the workflow."
        }

    - name: Checkout Current Repository
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: xvfb-run -a npm run jest-test-summary

    - name: Check Jest Coverage and Results Summary
      shell: pwsh
      run: . .github/workflowScripts/checkJestTestCoverage.ps1
